// For Sales
export const RECEIVE_ALL_FOR_SALES = 'RECEIVE_FOR_SALES';
export const SELECT_SINGLE_FOR_SALE = 'SELECT_SINGLE_FOR_SALE';
export const ADD_FOR_SALE_PROPERTY = 'ADD_FOR_SALE_PROPERTY';
export const DELETE_FOR_SALE_PROPERTY = 'DELETE_FOR_SALE_PROPERTY';

// For Rents
export const RECEIVE_ALL_FOR_RENTS = 'RECEIVE_ALL_FOR_RENTS';
export const SELECT_SINGLE_FOR_RENT = 'SELECT_SINGLE_FOR_RENT';
export const ADD_FOR_RENT_PROPERTY = 'ADD_FOR_RENT_PROPERTY';
export const DELETE_FOR_RENT_PROPERTY = 'DELETE_FOR_RENT_PROPERTY';
